[module/cpu]
type = internal/cpu
interval = 2

format = <label>
format-background = ${colors.background}
format-padding = 1
format-prefix = "󰘚 "
format-prefix-foreground = ${colors.primary}

label = %percentage:2%%

; vim:ft=dosini
