[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /

format-mounted = <label-mounted>
format-mounted-background = ${colors.background}
format-mounted-padding = 1
label-mounted = %{F#fbcb97}󰋊%{F-} %used%

format-unmounted = <label-unmounted>
format-unmounted-background = ${colors.background}
format-unmounted-padding = 1
label-unmounted = 󰋊 %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

; vim:ft=dosini
