[module/memory]
type = internal/memory
interval = 2

format = <label>
format-background = ${colors.background}
format-padding = 1
format-prefix = "󰍛 "
format-prefix-foreground = ${colors.primary}

label = %used%

; vim:ft=dosini
