; Not in layout.ini -- defined and ready, add wlan or eth to an island run.
[network-base]
type = internal/network
interval = 5

format-connected = <label-connected>
format-connected-background = ${colors.background}
format-connected-padding = 1

format-disconnected = <label-disconnected>
format-disconnected-background = ${colors.background}
format-disconnected-padding = 1
label-disconnected = %{F#888888}󰌙 %ifname%%{F-}

[module/wlan]
inherit = network-base
interface-type = wireless
label-connected = %{F#fbcb97}󰖩%{F-} %essid%

[module/eth]
inherit = network-base
interface-type = wired
label-connected = %{F#fbcb97}󰈀%{F-} %local_ip%

; vim:ft=dosini
