[module/pulseaudio]
type = internal/pulseaudio

format-volume = <label-volume>
format-volume-background = ${colors.background}
format-volume-padding = 1
format-volume-prefix = "󰕾 "
format-volume-prefix-foreground = ${colors.primary}
label-volume = %percentage%%

format-muted = <label-muted>
format-muted-background = ${colors.background}
format-muted-padding = 1
label-muted = 󰝟 muted
label-muted-foreground = ${colors.disabled}

; vim:ft=dosini
